config/routes.rb
Rails.application.routes.draw do
  get ":file_name", to: "static_pages#show", constraints: {file_name: 
    /#{Rose::Application::STATIC_PAGES.join("|")}/}
  root "static_pages#home_page"
  devise_for :staffs
  namespace :manage do
    root "people#index"
    resources :campaigns do
      resources :people
    end
    resources :campaign_people, as: :camp_people
    resources :people
    resources :students
    resources :staffs do
      resources :staff_sales
    end
    resources :klasses do
      resources :student_klasses
      resources :lectures
      resources :students
    end
  end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :campaign_staffs
  has_many :staffs, through: :campaign_staffs
  has_many :campaign_people
  has_many :people, through: :campaign_people

  validates :name, :location, :date, presence: true
end

app/models/campaign_person.rb
class CampaignPerson < ActiveRecord::Base
  belongs_to :campaign
  belongs_to :person
  has_many :people_available_days
  has_many :m_days, through: :people_available_days, class_name: M::Day
end

app/models/campaign_staff.rb
class CampaignStaff < ActiveRecord::Base
  belongs_to :staff
  belongs_to :campaign
end

app/models/klass.rb
class Klass < ActiveRecord::Base
  has_many :student_klasses
  has_many :students, through: :student_klasses
  has_many :lectures

  validates :name, presence: true
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :klass

  validates :name, :klass_id, presence: true
end

app/models/m.rb
module M
  def self.table_name_prefix
    'm_'
  end
end

app/models/m/day.rb
class M::Day < ActiveRecord::Base
  has_many :people_available_days, foreign_key: :m_day_id
  has_many :campaign_people, through: :people_available_days
end

app/models/people_available_day.rb
class PeopleAvailableDay < ActiveRecord::Base
  belongs_to :campaign_person
  belongs_to :m_day, class_name: M::Day
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :campaign_people
  has_many :campaigns, through: :campaign_people

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PHONE_REGEX = /\A[0-9\-\+]{9,15}\z/i

  validates :name, presence: true
  validates :email, :phone, allow_blank: true, uniqueness: {case_sensitive: false}
  validates :email, allow_blank: true, format: {with: VALID_EMAIL_REGEX}
  validates :phone, allow_blank: true, format: {with: VALID_PHONE_REGEX}

  before_validation :format_phone_number
  before_validation :format_email

  accepts_nested_attributes_for :campaign_people, allow_destroy: true

  def has_email?
    self.email.present?
  end

  def has_phone?
    self.phone.present?
  end

  def is_student?
    self.type == Student.name
  end

  def format_phone_number
    if self.phone.present?
      self.phone = self.phone.scan(/\d/).join
      self.phone = "0#{self.phone}" unless self.phone.start_with? "0"
    end
  end

  def format_email
    self.email = self.email.downcase if self.email.present?
  end
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
    :validatable

  has_many :campaign_staffs
  has_many :campaigns, through: :campaign_staffs
end

app/models/staff/admin.rb
class Staff::Admin < Staff; end

app/models/staff/general.rb
class Staff::General < Staff; end

app/models/staff/sale.rb
class Staff::Sale < Staff; end

app/models/staff/teacher.rb
class Staff::Teacher < Staff; end

app/models/student.rb
class Student < Person
  has_many :student_klasses
  has_many :klasses, through: :student_klasses

  accepts_nested_attributes_for :student_klasses, allow_destroy: true
end

app/models/student_klass.rb
class StudentKlass < ActiveRecord::Base
  belongs_to :student
  belongs_to :klass

  validates_uniqueness_of :student_id, scope: :klass_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def show
    render params[:file_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaign_people_helper.rb
module CampaignPeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rose</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/layouts/manage.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rose" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Passion English Center</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "#"  %></li>
              <li><%= link_to "Link2", "#"  %></li>
              <li><%= link_to "Link3", "#"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Campaigns</li>
              <li><%= link_to "All Campaigns", manage_campaigns_path  %></li>
              <li><%= link_to "Create New Campaign", new_manage_campaign_path  %></li>
              <li class="nav-header">People</li>
              <li><%= link_to "All People", manage_people_path %></li>
              <li><%= link_to "All Students", manage_students_path %></li>
              <li><%= link_to "Add New Person", new_manage_person_path %></li>
              <li class="nav-header">Classes</li>
              <li><%= link_to "All Classes", manage_klasses_path %></li>
              <li><%= link_to "Add New Class", new_manage_klass_path %></li>
              <li class="nav-header">Staffs</li>
              <li><%= link_to "All Staffs", manage_staffs_path %></li>
              <li><%= link_to "Sale Staffs", manage_staff_staff_sales_path(current_staff) %></li>
              <li><%= link_to "Teachers", "#" %></li>
              <li><%= link_to "Add New Staff", new_manage_staff_path %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span10">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "alert alert-#{key}") %>
          <% end %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rose" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">
    <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Passion English Center</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", "#"  %></li>
              <li><%= link_to "Contact", "#"  %></li>
              <li><%= link_to "About", "#"  %></li>
            </ul>
            <ul class="nav pull-right">
              <li><%= link_to "Sign In", "#"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <%= yield %>
    <footer class="footer">
      <p class="text_footer">&copy; Company 2014</p>
    </footer>
  </body>
</html>

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize object.errors.count, "error" %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home_page.html.erb
<div class="bs-example">
  <div id="myCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>   
    <div class="carousel-inner">
      <div class="active item">
        <img src="http://t0.gstatic.com/images?q=tbn:ANd9GcROLyMW1ZioojsJprU1x9rp1hBJGY2x62Kvo3iX5ty5kaE2M6bY">
      </div>
      <div class="item">
        <img src="http://t3.gstatic.com/images?q=tbn:ANd9GcQuO0MSqW-7TOFPEgN7UeSjIRYL3X-q0yqRtWhL_J8lCSscUVf0">
      </div>
      <div class="item">
        <img src="http://t1.gstatic.com/images?q=tbn:ANd9GcSnFlVH9MoBUUT6w3Xq-F7yEuJnXitucD2eILfyievOVDnUN0Zl">
        </div>
      </div>
      <a class="carousel-control left" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="carousel-control right" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
  </div>
</div>
<div class="main">
  <div class="two-column1">
    <p>Hot</p>
    <ul class="thumbnails">
      <li>
        <div class="thumbnail">
          <img src="http://t1.gstatic.com/images?q=tbn:ANd9GcSnFlVH9MoBUUT6w3Xq-F7yEuJnXitucD2eILfyievOVDnUN0Zl" alt="">
          <h3>Thumbnail label</h3>
          <p>Thumbnail caption Thumbnail caption
            Thumbnail caption......</p>
        </div>
      </li>
    </ul>
  </div>
  <div class="two-column2">
  <div class="three-column"><p>News
    <ul class="thumbnails">
      <li>
        <div class="thumbnail">
          <img src="http://t1.gstatic.com/images?q=tbn:ANd9GcSnFlVH9MoBUUT6w3Xq-F7yEuJnXitucD2eILfyievOVDnUN0Zl" alt="">
          <h3>Thumbnail label</h3>
          <p>Thumbnail caption Thumbnail caption
            Thumbnail caption......</p>
        </div>
      </li>
      <li>
        <div class="thumbnail">
          <img src="http://t1.gstatic.com/images?q=tbn:ANd9GcSnFlVH9MoBUUT6w3Xq-F7yEuJnXitucD2eILfyievOVDnUN0Zl" alt="">
          <h3>Thumbnail label</h3>
          <p>Thumbnail caption Thumbnail caption
            Thumbnail caption......</p>
        </div>
      </li>
    </ul>
  </p>
  </div>
  <div class="three-column"><p>Learn</p>
    <ul class="thumbnails">
      <li>
        <div class="thumbnail">
          <img src="http://t1.gstatic.com/images?q=tbn:ANd9GcSnFlVH9MoBUUT6w3Xq-F7yEuJnXitucD2eILfyievOVDnUN0Zl" alt="">
          <h3>Thumbnail label</h3>
          <p>Thumbnail caption Thumbnail caption
            Thumbnail caption......</p>
        </div>
      </li>
      <li>
        <div class="thumbnail">
          <img src="http://t1.gstatic.com/images?q=tbn:ANd9GcSnFlVH9MoBUUT6w3Xq-F7yEuJnXitucD2eILfyievOVDnUN0Zl" alt="">
          <h3>Thumbnail label</h3>
          <p>Thumbnail caption Thumbnail caption
            Thumbnail caption......</p>
        </div>
      </li>
    </ul>

  </div>
  <div class="three-column"><p>Events</p>
    <ul class="thumbnails">
      <li>
        <div class="thumbnail">
          <img src="http://t1.gstatic.com/images?q=tbn:ANd9GcSnFlVH9MoBUUT6w3Xq-F7yEuJnXitucD2eILfyievOVDnUN0Zl" alt="">
          <h3>Thumbnail label</h3>
          <p>Thumbnail caption Thumbnail caption
            Thumbnail caption......</p>
        </div>
      </li>
      <li>
        <div class="thumbnail">
          <img src="http://t1.gstatic.com/images?q=tbn:ANd9GcSnFlVH9MoBUUT6w3Xq-F7yEuJnXitucD2eILfyievOVDnUN0Zl" alt="">
          <h3>Thumbnail label</h3>
          <p>Thumbnail caption Thumbnail caption
            Thumbnail caption......</p>
        </div>
      </li>
    </ul>
  </div>
  </div>
</div>